### PR TITLE
Week 4 Content

### PR DESCRIPTION
**Pull request by tongchunkit**

### CODE REVIEW

**Comment by damithc** [comment]
Use 4 spaces for each indentation level.
Need to resolve the merge conflict.

**Comment by tongchunkit** [comment]
Changed the indentation from tab to 4 spaces.

**Comment by damithc** [comment]
Can you resolve the merge conflict too?

**Comment by tongchunkit** [comment]
Can't seem to resolve the merge conflict automatically. SourceTree also reports nothing to merge. 

screen

**Comment by damithc** [comment]
Probably your master is behind. Sync with upstream.

**Comment by tongchunkit** [comment]
I think it should be fixed now.

**Comment by damithc** [comment]
Ensure the links to handbook sections are working. See week 2 for an example.

**Comment by tongchunkit** [comment]
The links should be working now.

**Pull request merged**
