### PR TITLE
Code with black text is hidden on black background #211

### LINKED ISSUE #211: Code with black text is hidden on black background
The `code` is hidden on `background-color: black`.
<br>

### PR DESCRIPTION
**Pull request by acjh**
Fixes #211 
[Preview](http://rawgit.com/acjh/website/211-code-black-text-hidden/contents/handbook.html#handbook-project-v04)

### CODE REVIEW

**Comment by damithc** [comment]
These texts used to have syntax highlighting. You can compare with the live version. Something must have broke in the commits during the last few days. http://www.comp.nus.edu.sg/~cs2103/AY1617S1/contents/handbook.html#

**Comment by damithc** [comment]
May be #194 got something to do with it? It was the recent PR that is most related to this feature.

**Comment by acjh** [comment]
Ah, my bad. The issue lies with #202, where in return for not freezing the page,
requeuing the ajax lets `document.ready` trigger `run_prettify.js` prematurely.

**Comment by acjh** [comment]
Workaround as a trade-off for not freezing the page?

| Before | After |
| --- | --- |
|  |  |

**Comment by damithc** [comment]
The preview is still all-black. 🤔

**Comment by acjh** [comment]
Did away with `$.holdReady` - running it after `jQuery.min.js` meant `document` might already have loaded.
Does this fix work reliably?

**Comment by damithc** [comment]
On a related note, @wkurniawan07 can you advise on putting scripts at the end of the page vs at the top? I remember you did something related in TEAMMATES.

**Comment by wkurniawan07** [comment]
Is anything from the `run_prettify` script vital enough to justify it being put on top? If not, (almost always) to put it at the bottom, which this PR rightly does. [Chapter 6 of this book](https://www.amazon.com/High-Performance-Web-Sites-Essential/dp/0596529309) (copies can be found online) gives the detailed breakdown of the different decisions.

**Pull request merged**
