### PR TITLE
Schedule page: Expand contents upon clicking subheadings #30

### LINKED ISSUE #30: Schedule page: Expand contents upon clicking subheadings
Revealing the contents upon clicking the subheadings (Deadlines, Things to Do, etc) may work better.
In the common cases of "what is there to do", or "what will happen during the tutorial", it's likely that the student will expand everything under the subheading in the end anyway.
While the current format do give a good summary, more information may be more beneficial than less for the students here.

### PR DESCRIPTION
**Pull request by jkt001**
Fixes #30 

Staged version is <a href = "http://jkt001.github.io/website/">here</a>.

The staged version is combined with PR #133 which is the PR for loading specific section in an embedded link.

### CODE REVIEW

**Comment by jkt001** [comment]
Update: I have fixed conflicts after master was updated. Ready for review again. Staged version is <a href = "http://jkt001.github.io/website/">here</a>. Staged version combined with #133

**Comment by wkurniawan07** [comment]
Just wondering, if clicking on the accordion header is the same as clicking the `++` button, then I think it's safe to say that `++` has outlived its usage?

**Comment by damithc** [comment]
Let's keep both. `++` is explicit while clicking on the panel header is implicit. But we should reuse code between the two as much as possible.

**Comment by jkt001** [comment]
The auto-expand behaviour is added such that it "clicks" the '++' button, hence it does not add any code besides adding the behaviour. 

If there's anything I should modify or add, just let me know.

**Comment by wkurniawan07** [comment]
Well the functionality does work. I just can't help the feeling that we should remove the "++" button altogether :p
Anyway, that would be another issue. This is good to go. :+1:

**Pull request merged**
