### PR TITLE
Remove pages for coding standards and update references #224

### LINKED ISSUE #224: Remove pages for coding standards and update references
Requested in [issues/222#issuecomment-267597549](https://github.com/nus-cs2103/website/issues/222#issuecomment-267597549)
> We should point to the versions in https://github.com/oss-generic/process/

#
- ~Update [reference to HTML coding standards](https://github.com/nus-cs2103/website/blame/958155c748576fa3a01a17cb9f14c71dbf9d0e99/README.md#L32) in README~ (moved to [DeveloperGuide](https://github.com/nus-cs2103/website/blame/master/doc/DeveloperGuide.md#L60))
- Update [reference to CSS coding standards](https://github.com/nus-cs2103/website/blame/master/doc/DeveloperGuide.md#L59) in DeveloperGuide
- Fix [reference to DeveloperGuide](https://github.com/nus-cs2103/website/blame/master/README.md#L13) in README

### PR DESCRIPTION
**Pull request by acjh**
Fixes #224
[Preview](https://github.com/acjh/website/blob/224-coding-standards-update-references/doc/DeveloperGuide.md#coding-standards)

### CODE REVIEW

**Comment by damithc** [comment]
We'll need to keep these files around for a bit longer because there are incoming links to them.

**Comment by acjh** [comment]
Oh, incoming links from where?

**Comment by damithc** [comment]
@acjh 

> Oh, incoming links from where?

The one I can remember is TEAMMATES.

**Comment by acjh** [comment]
Noted.

**Comment by damithc** [comment]
Can go ahead. I updated the link from TEAMMATES. This PR highlights the danger of doing multiple things in one PR. Because one of the multiple things got blocked, the other things got delayed as well :-)

**Comment by acjh** [comment]
Ready for review.

**Pull request merged**
