### PR TITLE
Add missing contributors to the CONTRIBUTORS.md #94

### LINKED ISSUE #94: Add missing contributors to the CONTRIBUTORS.md
These tutors helped to write the initial version of the Schedule page, but they are missing from the contributor list.
week 3: Junwei
week 4: Chun Kit
week 5: Lynnette
week 6: Ryan
week 7: Fazli
week 8: Karan
week 9: Asawari
week 10: Sebastian
week 11: Ian
week 12: Sam
week 13: Junchao

Their full names can be found in [this page](https://docs.google.com/document/d/12e7KRTiQYl9V2Ndz2pRSIFNfHoRuVjkbM6NPSuETPI4/pub?embedded=true) 

Their GitHub IDs can be found by digging through past PRs.

### PR DESCRIPTION
**Pull request by barnytan**
Fixes #94 

Not sure if the description of work done by is suitable.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Hi @barnytan, this is the 2nd `forFirstTimers` issue that you've worked on (the other one being #106). Can you close either one of them? I will then review the one that you keep.

**Comment by barnytan** [comment]
Hi @wkurniawan07, sorry I overlooked point 3 of the readme. I will close this one then.

**Comment by barnytan** [comment]
Also @wkurniawan07 should I delete this branch?

**Comment by wkurniawan07** [comment]
You're free to.

**Pull request closed without merging**
