### PR TITLE
Auto expand content for anchored links to schedule page #237

### LINKED ISSUE #237: Auto expand content for anchored links to schedule page
Requested in [pull/236#issuecomment-269107489](https://github.com/nus-cs2103/website/pull/236#issuecomment-269107489)
> e.g. [.../contents/schedule.html#activity-content-week2](http://nus-cs2103.github.io/website/contents/schedule.html#activity-content-week2)

### PR DESCRIPTION
**Pull request by acjh**
Fixes #237
Previews:
- [.../contents/schedule.html#header-content-week2](http://rawgit.com/acjh/website/237-auto-expand-anchor-schedule/contents/schedule.html#header-content-week2)
- [.../contents/schedule.html#activity-content-week2](http://rawgit.com/acjh/website/237-auto-expand-anchor-schedule/contents/schedule.html#activity-content-week2) (nested section)

### CODE REVIEW

**Comment by damithc** [comment]
Nice. Does this work for any anchor (e.g. if I put an anchor in the lowest level container) or are there any limitations?

**Comment by acjh** [comment]
At the moment, this is limited to the first nested level as required by the current Search page.

**Comment by acjh** [comment]
Let me try :)

**Comment by acjh** [comment]
Done!
Preview 3: [.../contents/schedule.html#ui-id-61](http://rawgit.com/acjh/website/237-auto-expand-anchor-schedule/contents/schedule.html#ui-id-61)

**Pull request merged**
