### PR TITLE
Update dashboard page 20161107

### PR DESCRIPTION
**Pull request by okkhoy**
latest status

### CODE REVIEW

**Comment by okkhoy** [comment]
errr... i just merged the upstream to my master, checked out; made my
changes and submitted this PR!

**Comment by damithc** [comment]
You should pull from upstream master to your master, not merge. Your local master should be tracking upstream master.  `git pull upstream master` (assuming you have a remote called upstream).

**Comment by damithc** [comment]
Forgot to update the date?

**Comment by okkhoy** [comment]
oops! let me fix it

**Pull request merged**
