### PR TITLE
add content to handbook-programmingLanguages.html

### PR DESCRIPTION
**Pull request by SeaOfOcean**
add content to handbook-programmingLanguages.html

### CODE REVIEW

**Comment by damithc** [comment]
Try to limit line length to about 110-120 characters. Other than that, looks fine. Comment here after adjusting the line length.

**Comment by SeaOfOcean** [comment]
you mean limit the length by css or the source html?

**Comment by damithc** [comment]
In the source code. Just insert line breaks. It won't affect how the page
is displayed but it will improve the readability of the code.

**Comment by SeaOfOcean** [comment]
Hi, Prof, can you see the new commit?

**Comment by damithc** [comment]
Merged. Good job. can move onto other parts. May be one pull request for each part?

**Comment by damithc** [comment]
If an image or a file is missing from the `images` folder or the `files` folder, go ahead and add it too.

**Comment by SeaOfOcean** [comment]
OK, thanks for your comments :)

**Pull request merged**
