### PR TITLE
Add a DeveloperGuide.md for developers of this website #215

### LINKED ISSUE #215: Add a DeveloperGuide.md for developers of this website
Can contain useful information for developers e.g. coding standards, how to stage changes, etc.

### PR DESCRIPTION
**Pull request by acjh**
Fixes #215 
[Preview](https://github.com/acjh/website/blob/215-add-developer-guide/doc/DeveloperGuide.md#developer-guide)

### CODE REVIEW

**Comment by damithc** [comment]
LGTM. 👍 Some of the tools can be given as 'Recommended' or as examples because they are not strictly necessary.

**Comment by acjh** [comment]
Should I update README to point to DeveloperGuide in this PR?

**Comment by damithc** [comment]
Sure, that's a good idea. In fact, some of the content in README can be moved to Dev guide?

**Comment by acjh** [comment]
Okay!

**Comment by acjh** [comment]
I've updated the [README](https://github.com/acjh/website/tree/215-add-developer-guide#source-code-for-the-cs2103-module-website) and [Developer Guide](https://github.com/acjh/website/blob/215-add-developer-guide/doc/DeveloperGuide.md#developer-guide).

**Comment by damithc** [comment]
Looks good @acjh 
Go ahead and merge.

**Pull request merged**
