### PR TITLE
Panels in Schedule page: allow loading content from other pages #231

### LINKED ISSUE #231: Panels in Schedule page: allow loading content from other pages
For the lowest level panels in the Schedule page (e.g. a panel for a specific activity such as T1A1), it's nice if we can load content from a separate file e.g. `activities/T1A1.html`. The loading can happen during the expansion.

### PR DESCRIPTION
**Pull request by acjh**
Fixes #231
[Preview](http://rawgit.com/acjh/website/231-load-other-during-expansion/contents/week.html?preview=2)

### CODE REVIEW

**Comment by damithc** [comment]
Nice!
Is it possible to tweak so that I can write this instead?

In parent page:
```html
<h3 class="load-during-expansion" data-url="activities/IDEs.html">T1A1. Get started with IDEs <img src="../images/star.png"/></h3>
```

IDEs.html:
```html
<span class="dim">The single <img src="../images/star.png"/> above indicates this is a
        <span onclick="getContentUsingAjax('handbook-tutorials', '#embedded-t1a1');">
          <span class="embedded-link">BASIC learning activity</span>
        </span>.
		</span>
        <div id="embedded-t1a1"></div>
        Go to the <a href="https://github.com/nus-cs2103-AY1617S2/addressbook-level1" target="_blank">addressbook-level1</a> project.
        Do the exercise under the following learning outcomes.
        <ol type="a">
           <li><a href="https://github.com/nus-cs2103-AY1617S2/addressbook-level1#set-up-a-project-in-an-ide-lo-idesetup" target="_blank">
            AddressBook-Level1: Set up a project in an IDE [LO-IdeSetup]</a></li>
           <li><a href="https://github.com/nus-cs2103-AY1617S2/addressbook-level1#navigate-code-efficiently-lo-codenavigation" target="_blank">
             AddressBook-Level1: Navigate code efficiently [LO-CodeNavigation]</a></li>
        </ol>
       <p>
          Submission: Demo your code and code navigation skills to the tutor during the tutorial.
       </p>
```

**Comment by acjh** [comment]
Sure, I can do that.

**Comment by damithc** [comment]
Great. That way, the html file is easier to reuse from different places, using different titles to match the context.

**Comment by acjh** [comment]
@damithc Done!

**Comment by damithc** [comment]
Looks good. Need to update content author guide too?

**Comment by acjh** [comment]
Sure, I'll get to that tonight.

**Comment by acjh** [comment]
Should I move all the other panels or separate PR?

**Comment by damithc** [comment]
> Should I move all the other panels or separate PR?

That should be a separate PR and not urgent either. Just leave it as an open issue for now.

**Comment by acjh** [comment]
Added info in [ContentAuthorGuide.md#component-panels](https://github.com/acjh/website/blob/231-load-other-during-expansion/doc/ContentAuthorGuide.md#component-panels)

**Pull request merged**
