### PR TITLE
Handbook page: merge appendix C (FAQ) into a single file #148

### LINKED ISSUE #148: Handbook page: merge appendix C (FAQ) into a single file
Currently each FAQ is in a separate file. 
See appendix B (policies) for an example.

### PR DESCRIPTION
**Pull request by Stevan0102**
Fixes #148

### CODE REVIEW

**Comment by acjh** [comment]
Hi Stevan, your PR should be from <a href="https://github.com/Stevan0102/website/tree/148-Handbook-Merge-FAQ">```148-Handbook-Merge-FAQ```</a> instead of your <a href="https://github.com/Stevan0102/website/tree/gh-pages">```gh-pages```</a> branch.
You can link your <a href="http://stevan0102.github.io/website">Preview</a> with ```<a href="http://stevan0102.github.io/website">Preview</a>``` :)

**Comment by damithc** [comment]
Yup, please create a new PR with the correct branch.

**Comment by wkurniawan07** [comment]
@Stevan0102 your previous PR #170 is more correct.

**Comment by Stevan0102** [comment]
@acjh , @wkurniawan07 Thanks guys for your suggestion!

**Pull request closed without merging**
