### PR TITLE
Add reading week to the sechdule #61

### LINKED ISSUE #61: Add reading week to the sechdule
e.g. deadline for project retrospective

### PR DESCRIPTION
**Pull request by crispyfridge**
Fixes #61
week14.html was created for recess week, but I wasn't sure what content to put in, so I just included the section for deadlines and things to do.

### CODE REVIEW

**Comment by damithc** [comment]
Link to preview?

**Comment by crispyfridge** [comment]
The link to preview is here:
http://crispyfridge.github.io/website/

**Comment by damithc** [comment]
The preview page does not show reading week in the schedule.

**Comment by crispyfridge** [comment]
I've made the changes. Sorry for the confusion

**Comment by damithc** [comment]
There are two deadlines in reading week: project retrospective and individual report.

**Comment by crispyfridge** [comment]
I've added the deadlines.
Link: http://crispyfridge.github.io/website/

**Comment by damithc** [comment]
Good. Can you also link to relevant sections in the handbook? Refer V0.5 deadlines for an example.

**Comment by crispyfridge** [comment]
I've added the links to the relevant sections in the handbook.
Link: http://crispyfridge.github.io/website/

**Comment by damithc** [comment]
I have no further suggestions. @wkurniawan07 any comments?

**Comment by damithc** [comment]
@crispyfridge now you have permission to change labels. You can use labels to indicate when a PR is ready for review.

**Comment by crispyfridge** [comment]
@damithc Ok noted~

**Comment by wkurniawan07** [comment]
Looks good :+1:

**Comment by damithc** [comment]
Reminder: If you wish to add your name to the CONTRIBUTORS.md, you may do so by submitting another PR. :-)

**Pull request merged**
