### PR TITLE
Style guides: set a max width for the page content #158

### LINKED ISSUE #158: Style guides: set a max width for the page content
It is better to set a max width for the page. Otherwise the content become hard to read when using a wide screen browser.

### PR DESCRIPTION
**Pull request by acjh**
Fixes #158
Previews: <a href="http://acjh.github.io/website/contents/coding-standards-cpp.html">cpp</a>, <a href="http://acjh.github.io/website/contents/coding-standards-html.html">html</a>, <a href="http://acjh.github.io/website/contents/coding-standards-java.html">java</a> coding standards

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Good job :+1:
I won't say that this is the actual fix for #157 though, because it _just happens_ to fix it. The actual fix will be adding a `<br>`, just like what is done for the Java coding style. So this PR shouldn't close that issue.

**Comment by damithc** [comment]
I thought the page width is a css issue? Using <br> to control pad width is going to be quite messy and fragile.

**Comment by wkurniawan07** [comment]
Ah no that's not relevant to this issue. It's about #157 the Dennis Ritchie text on the side of the picture, clearly caused by a missing `<br>`.

**Comment by damithc** [comment]
Understood :-)

**Comment by acjh** [comment]
Noted, but I suggest to specify on #157 since that issue won't seem obvious anymore after this PR.

**Comment by damithc** [comment]
Good idea @acjh. Can you add a comment there?

**Comment by acjh** [comment]
Done!

**Pull request merged**
