### PR TITLE
Handbook TOC links are not working in iPhone browser #19

### LINKED ISSUE #19: Handbook TOC links are not working in iPhone browser
These links don't seem to be working in iPhone browser
image

### PR DESCRIPTION
**Pull request by acjh**
Fixes #19
[Preview](http://rawgit.com/acjh/website/19-handbook-links-in-iphone/)

### CODE REVIEW

**Comment by acjh** [comment]
As it turns out, Apple doesn't like creating compatible products.
I managed to get my hands on an iPad just now and noticed that Safari doesn't scroll *within* frames.
The solution is to make `window.top` scroll instead.

Note: Actually, this problem is not limited to `handbook` TOC links, but **all** anchor links within frames.

**Comment by damithc** [comment]
Works for me in iPhone6/Safari

**Comment by acjh** [comment]
Shall I merge this?

**Comment by damithc** [comment]
Yes, go ahead.

**Pull request merged**
