### PR TITLE
34-format and picture week5

### PR DESCRIPTION
**Pull request by quarbby**
- Correcting the format and the missing picture
- Reduced 4 spaces to 2 spaces

### CODE REVIEW

**Comment by damithc** [comment]
Can you post a screenshot of how the week 5 lecture section looks?

**Comment by quarbby** [comment]
Here is a screenshot
capture

**Comment by damithc** [comment]
What about lecture 5 part 2?

**Comment by quarbby** [comment]
Part 2 looks like this:
capture2

**Pull request merged**
