### PR TITLE
week 11

### PR DESCRIPTION
**Pull request by ianngiaw**

### CODE REVIEW

**Comment by damithc** [comment]
Can limit the line length to about 110-120 chars?

**Comment by ianngiaw** [comment]
For sentences longer than 120 characters, do I just add a break midway?

**Comment by damithc** [comment]
Anywhere is fine. Break somewhere near 110 chars? The break (\n)  is only
in the html source. It wont appear in the actual web page.

**Comment by ianngiaw** [comment]
Oh I thought by break you meant adding <br>

**Pull request merged**
