### PR TITLE
Handbook TOC links are not working in iPhone browser #19

### LINKED ISSUE #19: Handbook TOC links are not working in iPhone browser
These links don't seem to be working in iPhone browser
image

### PR DESCRIPTION
**Pull request by crispyfridge**
Fixes #19 
It seems that the `handbook.js` interfered with how the links worked, since the links work fine without the js file, but I'm not sure what is causing that. 
I added empty divs with ids that don't overlap with those that the js is using, and it worked fine.
preview: http://crispyfridge.github.io/website/

### CODE REVIEW

**Comment by damithc** [comment]
May be it's worth figuring out what caused the problem, to avoid it recurring or to avoid breaking something while we are trying to fix this one.

**Comment by crispyfridge** [comment]
From what I read [here](http://www.webdeveloper.com/forum/showthread.php?259280-anchor-tag-not-working-in-safari-(ios)-for-Iphone-iTouch-iPad), it seems that this is a problem unique to iOS. Also, I've tested the site on an android device prior the fix and it works fine.

**Comment by damithc** [comment]
I meant how did this change fix the problem?

**Comment by crispyfridge** [comment]
It was a workaround that I found online, but there wasn't any particular explanation to why it worked.

**Comment by damithc** [comment]
Let's wait to see if @wkurniawan07 has any insights about this.

**Comment by wkurniawan07** [comment]
I'm afraid not, I'm not an iPhone user. I do have an iPad though, and even the current version (before this fix) actually works. @crispyfridge where exactly do you find the workaround?

**Comment by crispyfridge** [comment]
@wkurniawan07 [I got it here](http://answers.squarespace.com/questions/63483/why-wont-my-anchor-links-work?page=1#67402) 
At first I didn't really focus on this solution because it seems like that's what the original code is already doing. I eventually added a new div like the solution suggested when other workarounds failed, and it worked.

**Comment by damithc** [comment]
I used my iPhone to access your staged handbook page from direct URL as well as via home page. Links worked in both cases.

**Comment by crispyfridge** [comment]
@damithc Sorry I shouldn't have used the staged website as an example. The staged website contains the fix, so it works. I wanted to say that before the fix, using mobile, the links in the handbook page from the direct URL works, but the links in the handbook page when accessed from the home page doesn't work.

**Comment by damithc** [comment]
Got it :-)

**Comment by wkurniawan07** [comment]
@crispyfridge maybe you can push it to `gh-pages`, and I'll try it on my PC, android phone, as well as iPad. If it works on my devices and works on iPhones (which I can't confirm) as well, this should be good to go.

**Comment by crispyfridge** [comment]
@wkurniawan07 I've pushed it to gh-pages. You can try it here: http://crispyfridge.github.io/website/

**Comment by damithc** [comment]
Position and size of overlay is off screen on iPhone 6. Make width fixed
and position near to top?

-- 
Sent from a mobile device.

**Comment by damithc** [comment]
Can do as a separate issue.

-- 
Sent from a mobile device.

**Comment by crispyfridge** [comment]
@damithc I've created a separate issue for it

**Comment by wkurniawan07** [comment]
Strange, it doesn't work on my iPad. Even the current version (before this fix) fails now, I could've sworn it worked 2 days ago.
I have a feeling it has something to do with how mobile Safari interprets frames, because the links in the standalone handbook page work just fine.

**Comment by crispyfridge** [comment]
@wkurniawan07 Would it be better if I replaced the frame and frameset in `index.html` with `<iframe>` instead? Or should I use divs?

**Comment by wkurniawan07** [comment]
Divs won't work unless all of the pages used are within our control, which are not (e.g we have the IVLE page and some Google docs page). I haven't tried `iframe` myself, feel free to try it and share the result.

**Comment by damithc** [comment]
Any progress? As a last resort, we can implement the the thing that 'seems to work' although we don't understand why it works. It's not ideal but better than nothing :-)

**Comment by crispyfridge** [comment]
I managed to replace the frames with `iframe`, but it doesn't work on my iphone with the original div ids :(

**Comment by wkurniawan07** [comment]
@crispyfridge I haven't checked on this for a while. Any updates?

**Comment by crispyfridge** [comment]
@wkurniawan07 sorry for the late reply. I haven't been working on this for a while now, so no updates

**Comment by acjh** [comment]
I appreciate any help to test the fix in PR #216 please :)

**Comment by acjh** [comment]
Fixed in #216

**Pull request closed without merging**
