### PR TITLE
Organise files inside contents #127

### LINKED ISSUE #127: Organise files inside contents
Currently, the contents inside the contents folder is mixed, i.e. the content for handbook is mixed with schedule, coding style, etc. 

A good practice is to create subfolders for each type of content, i.e.

contents/handbook/...
contents/schedule/...
contents/coding-style/...
etc.

e.g. 
contents/schedule/week0.html
contents/handbook/handbook-lectures.html

and then update all references to the organised files.

if my suggestion is ok, I will do this as soon as possible.

### PR DESCRIPTION
**Pull request by acjh**
Fixes #127 
- [x] Move related files into `handbook/`
  - [x] ...including `testingFaq.html` which is only referenced by `week4.html`
  - [x] `handbook.html` → `handbook/index.html`
- [x] Move related files into `schedule/`
  - [x] `schedule.html` → `schedule/index.html`
- [x] Move related files into `../codingStandards/`
- [x] Move related files into `search/`
  - [x] `search.html` → `search/index.html`
- [x] Move related files into `examples/`
  - `A123456.md`
  - `AboutUs.md`
- [x] Miscellaneous
  - [x] Move `Teams-AY1617S2.md` into `../dashboard/`
  - [x] Create issue for `pointsToPonderAboutProductDesign.html` (see #250)

> Note: Paths are relative to `.../contents/`

## Directory Structure
- Upstream: [.../contents/](https://github.com/nus-cs2103/website/tree/master/contents)
- PR branch: [.../contents/](https://github.com/acjh/website/tree/127-organise-files-in-contents/contents)

### CODE REVIEW

**Comment by acjh** [comment]
## Phase 2: Schedule
- [.../contents/schedule.html](http://rawgit.com/acjh/website/127-organise-files-in-contents/contents/schedule.html)
- [.../contents/week.html?preview=6](http://rawgit.com/acjh/website/127-organise-files-in-contents/contents/week.html?preview=6)
- [.../index.html](http://rawgit.com/acjh/website/127-organise-files-in-contents/index.html)

**Comment by acjh** [comment]
@damithc Some points to highlight:
1. The file `.../contents/pointsToPonderAboutProductDesign.html` is unreferenced.
1. Should `.../contents/handbook.html` be `.../contents/handbook/index.html`?
1. Should `.../contents/schedule.html` be `.../contents/schedule/index.html`?

**Comment by damithc** [comment]
> The file .../contents/pointsToPonderAboutProductDesign.html is unreferenced.
I see. Please create an issue for it.

> Should these files be in their respective subdirectories?
>     .../contents/handbook.html → .../contents/handbook/index.html
>     .../contents/schedule.html → .../contents/schedule/index.html
>     .../contents/search.html → .../contents/search/index.html

Sure.

**Comment by acjh** [comment]
@damithc I realized that moving `handbook.html` to `handbook/index.html` means links like `handbook.html#preliminaries` become `handbook/index.html#preliminaries` (option 1) or `handbook/#preliminaries` (option 2). I'm inclined to option 2 to avoid unnecessary verbosity.

Your thoughts on this?

**Comment by damithc** [comment]
Option 1 is more natural?

**Comment by acjh** [comment]
I thought so. Okay, I'll leave it as option 1.

**Comment by acjh** [comment]
These 2 files have extensive changes and are not recognized as moved files by GitHub.
- [.../contents/handbook/gradeBreakdown.html](https://github.com/nus-cs2103/website/pull/249/files#diff-32c0bb6e22692e5ae4ecff55d56c637c)
- [.../contents/handbook/index.html](https://github.com/nus-cs2103/website/pull/249/files#diff-40e526da7ac07b2e00c0e49c58a96e84)

These 2 files contain diffs of automatic removal of whitespace at the end of lines by Atom.
- [.../contents/handbook/preliminaries.html](https://github.com/nus-cs2103/website/pull/249/files#diff-466d7ebcba424ff0fc9a31af8d3979f0)
- [.../contents/handbook/testingFaq.html](https://github.com/nus-cs2103/website/pull/249/files#diff-ce83548edc649f88c0fefb183700a152)

**Pull request merged**
