### PR TITLE
Handbook page: merge appendix C (FAQ) into a single file #148

### LINKED ISSUE #148: Handbook page: merge appendix C (FAQ) into a single file
Currently each FAQ is in a separate file. 
See appendix B (policies) for an example.

### PR DESCRIPTION
**Pull request by Stevan0102**
Fixes #148 
<a href="http://stevan0102.github.io/website">Preview</a>
Merged all Appendix C contents (faqs) into a single file (Just like Appendix B)

### CODE REVIEW

**Comment by Stevan0102** [comment]
Sorry, did not follow the requirement. Will recreate one that follows the instruction

**Comment by wkurniawan07** [comment]
Your branch name looks correct, so I don't see the reason why not to continue here. If the problem is wrong issue title and PR description, it can be rectified without closing the PR :p but of course it's up to you.

**Comment by acjh** [comment]
@Stevan0102 Can you sync this with the master branch to make it ready for review?

**Comment by acjh** [comment]
Fixed in #201

**Pull request closed without merging**
