### PR TITLE
Make the whole page scrolls- alternative fix #41

### LINKED ISSUE #41: Make the whole page scrolls
Currently only the div#content scrolls when content overflows (i.e., when sections are expanded).
However, since there are no other content, it's more natural for the whole page to scroll.

### PR DESCRIPTION
**Pull request by HooDeLin**
Fixes #41 
Staging site is [here](http://hoodelin.github.io/website)

This is an alternative fix. The previous fix is #104

### CODE REVIEW

**Comment by damithc** [comment]
I prefer this one. @wkurniawan07 ?

**Comment by damithc** [comment]
BTW, it looks like we can stage only one version at a time.

**Comment by wkurniawan07** [comment]
I don't have a particular preference. The trade-off for this version is the preference bar won't be so accessible when the user is so far down the page.
On an unrelated note, yes `gh-pages` can only stage one version of change at a time, unless the changes are independent (let's say this and a markdown conversion change).

**Comment by damithc** [comment]
OK, let's go for this one then. I don't think the preference panel will be used often, so it makes sense not to allocate permanent screen real estate to it. If users don't like it, we can revert. @wkurniawan07 please proceed to review and merge.

**Pull request merged**
