### PR TITLE
Handbook 'jump to section' hides the section title under the nav bar #20

### LINKED ISSUE #20: Handbook 'jump to section' hides the section title under the nav bar
When we jump to a section by clicking on a link in the table of contents, the section title is hidden under the nav bar.
image

### PR DESCRIPTION
**Pull request by bobby-lin**
Fixes #20 using jQuery animate() method.

### CODE REVIEW

**Comment by damithc** [comment]
I would like to have a preview of how it works. Can you push it to `gh-pages` branch so that we can access it from `github.io`. Something like [this](http://wkurniawan07.github.io/website/).

**Comment by bobby-lin** [comment]
Here is a preview: http://bobby-lin.github.io/website

**Comment by damithc** [comment]
@wkurniawan07 for your review please.

**Comment by wkurniawan07** [comment]
Looks good :+1:

**Pull request merged**
