### PR TITLE
Code samples in embedded content are blacked out #228

### LINKED ISSUE #228: Code samples in embedded content are blacked out
Specifically, this case:
https://rawgit.com/nus-cs2103/website/master/index.html

image

### PR DESCRIPTION
**Pull request by acjh**
Fixes #228 
[Preview](http://rawgit.com/acjh/website/228-code-samples-blacked-out/contents/week.html?preview=11)

### CODE REVIEW

**Comment by damithc** [comment]
LGTM 👍

**Comment by acjh** [comment]
I updated `handbook.js` to also call `prettyPrint` on demand, instead of `$.holdReady()`.

**Comment by damithc** [comment]
Seems to work. 👍

**Comment by damithc** [comment]
@acjh merge this one?

**Pull request merged**
