### PR TITLE
Auto-expand the current week of the schedule page

### LINKED ISSUE #33: Auto-expand the current week of the schedule page
Auto expanding the current week and auto-scrolling it may be useful?

### PR DESCRIPTION
**Pull request by sihaoo**
Fixes #33 

Added the enhancement to auto-expand the current week. Current week is determined by the date provided on the row.

Preview available: http://experiment.thewhiteconcept.com/sh/cs2103_website/
The preview has set Week 13 [Dec 28] to be the current week.

### CODE REVIEW

**Comment by damithc** [comment]
1. The week needs to expand fully
2. The start day of the semester should be defined somewhere. Once this date is set at the beginning of the semester, the auto-expand functionality should work for the entire semester.

**Comment by sihaoo** [comment]
1. I will make changes to expand the week fully.
2. The current implementation will detect the date in the row and expands the one that matches the same start of the week of the today's date. This will reduce the need to make changes every semester, will this solution work?

**Comment by damithc** [comment]
2. Yes, that sounds fine too. #124 might be relevant here too.

**Comment by sihaoo** [comment]
Thanks, I will take a look. I will commit the changes for the week expansion first!

**Comment by wkurniawan07** [comment]
Now that #124 has been merged, there might be some functions you can re-use.
Also, you don't have to resort to external server to stage your changes. `gh-pages` will do just fine. Of course it's up to you.

**Comment by sihaoo** [comment]
Yeah, I will make the changes with functions from #124 
Thanks for the advice, I will stage with 'gh-pages' for future pull requests.

**Comment by wkurniawan07** [comment]
You shouldn't manually add things from other commits, instead you should sync this PR with the current master by merging. You should do it soon because GitHub says there are conflicts that need resolving.

**Comment by sihaoo** [comment]
@wkurniawan07 Do you mind advising me what I should do about it? I did sync my repo before working on it. Seems like there is some issue with the branch, perhaps I did something wrong.

**Comment by wkurniawan07** [comment]
I checked your fork. You did sync your `master` branch, but not _this_ branch. All you need to do is running this command when in this branch: `git merge master`.

**Comment by wkurniawan07** [comment]
@sihaoo here too, any updates?

**Comment by acjh** [comment]
@sihaoo Do you still want to tidy up this PR?

**Comment by acjh** [comment]
Fixed in PR #219

**Pull request closed without merging**
