### PR TITLE
Fix size and position of 'Page Loading...' overlay in handbook page #112

### LINKED ISSUE #112: Fix size and position of 'Page Loading...' overlay in handbook page
Position and size of overlay is off screen on iPhone 6. Make width fixed
and position near to top

### PR DESCRIPTION
**Pull request by crispyfridge**
Fixes #112 
I'm still unable to resolve the blank page problem on the handbook. When I tested the handbook page using the master branch, I have the same problem.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Any demo so I can see how it looks like?

**Comment by crispyfridge** [comment]
@wkurniawan07 Here is the link: http://crispyfridge.github.io/website/
Sorry it took so long

**Comment by damithc** [comment]
I tried the staging site just now, using desktop chrome. The overlay did not appear and the TOC did not appear until the whole page is loaded (it was blank for a long time).

**Comment by crispyfridge** [comment]
Yeah, I can't find what's causing it. The blank page happens even when I remove the overlay entirely.

**Comment by damithc** [comment]
May be an auto-merge along the way did something it was not supposed to do? Try creating a new branch from the latest master and manually doing the change again.

**Comment by crispyfridge** [comment]
I pulled the latest commits from upstream to my fork's master branch, and tested it on local server. I still have a blank page when I load the handbook page. I cloned the same master branch onto the gh-pages branch and got the same result when I tested it remotely. I'm not sure if it affects only me.
Preview to master branch: http://crispyfridge.github.io/website/

**Comment by damithc** [comment]
Yes, the blank page this is affecting everybody. Even the live version has it :-) Go back in history to figure out exactly which commit started it?

**Comment by crispyfridge** [comment]
Alright, I'll hunt for the commit~
Glad to know it's not only affecting me, was worried that I was doing something wrong and didn't know

**Comment by wkurniawan07** [comment]
@crispyfridge here too, any updates?

**Comment by acjh** [comment]
Fixed in #202

**Pull request closed without merging**
