### PR TITLE
Week 12 content

### PR DESCRIPTION
**Pull request by mauris**

### CODE REVIEW

**Comment by damithc** [comment]
Can limit line length to about 110 chars?

**Comment by mauris** [comment]
reduced line lengths Prof!

**Comment by damithc** [comment]
Still there are many lines that are very long. May be your editor auto-wrap lines so you might not see them as long. Check the GitHub diff view to identify long lines.

**Comment by damithc** [comment]
Can finish this soon?

**Comment by mauris** [comment]
@damithc I have further reduced the lines length

**Comment by damithc** [comment]
Some lines are still too long, as you can see from this scroll bar in the diff view. Reducing the indentation to 2 spaces might help. 
image

**Comment by damithc** [comment]
This PR is contaminated by unrelated files.

**Comment by damithc** [comment]
@mauris this is the last remaining one. Let's finish it soon. If this PR is hard to fix, can open a new one.

**Pull request closed without merging**
